#### Data Analysis:

#### Data:
    - it is a collection of files
    - it contains raw information

#### Types of Data:
    - Structured Data
            - it is a tabualr format(columns/rows)
    - Un Structured Data
            - it does not have proper structure
                    ex: photos,videos,ppts,logfiles,voices,pdf files...
    - Semi Structured Data
            - .html files,xml files,json files

#### Types of Data In Statistics
    - Numerical Data:
            - it is a number format
            - made of numbers
                    ex: age,weight,no of childerns....
                    
                 - continuous Data
                         - infinite oprtions
                                 ex: age,weight,blood type
                 - Discreate Data
                         - finite opetions
                                 ex: shoesize,no of childrens
    - categorical Data
            - it is string format
            - made of words
                    ec: eye color,genders,blood type.....
                    
                   - ordinal Data
                           - data has follow proper hierarchy
                                   ex: surveys,ratings....
                   - Nominal Data
                           - data has not follow hierarchy
                                   ex:eyecolor,blood type....





#### python librarires for Data Analysis:

            - numpy
                    - numpy means numerical python
                    - it is used to craete multi dimensional arrays in python
            - pandas
                    - by using this we create tables to the data
                    - pandas is the most popular python library in data analysis,it provides highly optimized performance with backend sources
                    
                    
            - matplot lib
                    - by using library we can create graphs,plot,charts in python
                            ex: liner,bar,pie,histogram,box,area....
            - seaborn
                    - by using library we can design visualization on pandas data sets.



##### Numpy:
    - Numpy stands for numerical python
    - it is used for scientific computation ,it provides an efficient interface to store and opearte
    on data buffers.
    - by using this library we can create multi dimensional arrays in python
    
    
#### Library installation
    - pip install package name
        ex: pip install numpy
        
        
##### Numpy Arrays:
    - An array is a collection of homogeneous data which can represented as a 32 dimensions in numpy.
        - syntax:
        
                - numpy.array(data)

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
#### importing the librarry
import numpy as np

#### How to create arrays in numpy?
        -np.array(data)

In [5]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

#### How to access array elements:
        - index
                - index position starts with 0
                - synatx:
                        array_variable[index position]
        - slicing
                - if you want to access more than one elemenet at a time from the array
                - syntax:
                        array_variable[start_index:end+index+1:step value]

In [21]:
print(a)
print(a[4])
print(a[0:5])
print(a[:])
print(a[0:3])
print(a[:3])
print(a[2:5])
print(a[2:])
print(a[::-1])
print(a[0:5:2])
print(a[::2])
print(a[::-2])

[1 2 3 4 5]
5
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3]
[1 2 3]
[3 4 5]
[3 4 5]
[5 4 3 2 1]
[1 3 5]
[1 3 5]
[5 3 1]


#### Array Methods:
        - ndim()
            - it returns dimensions of an array
        - dtype()
            - it returns data type of an array
        - shape()
            - it returns no of rows and no of columns from an array
        - size()
            - it returns total elements size  of an array
        - nbytes()
            - it returns no of bytes of an array
        - itemsize()
            - it returns each element size in bytes format

In [28]:
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.nbytes)

[1 2 3 4 5]
1
int32
(5,)
5
4
20


#### arange()--->array range
    - synatx:
            np.arange(start range,end range +1,step value)

In [29]:
a1=np.arange(1,11)
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
a1=np.arange(1,31,2)
a1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [32]:
a2=np.arange(0,100,2)
a2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [33]:
a3=np.arange(1,100,2)
a3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

##### append()

In [34]:
print(a)

[1 2 3 4 5]


In [36]:
a4=np.append(a,10)
a4

array([ 1,  2,  3,  4,  5, 10])

In [37]:
a5=np.append(a,[90,78,56])
a5

array([ 1,  2,  3,  4,  5, 90, 78, 56])

#### ones():

    - np.ones(size)


In [38]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

#### zeros()
    - np.zeros(size)

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
np.zeros((4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### full():
    np.full(size)

In [46]:
np.full(5,"numpy")

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy'], dtype='<U5')

In [49]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [50]:
np.full((2,3),45)

array([[45, 45, 45],
       [45, 45, 45]])

In [51]:
np.full((4,5),"python")

array([['python', 'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python', 'python']], dtype='<U6')

#### np.linspace(start range,end range,no partitions)

In [52]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [53]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

#### 2-d Array:
    - it is a combination of more than one 1-d array
    - syntax:
            np.array([[e1,e2,e3,e4],[e1,e2,e3,e4]])

In [54]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [61]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)

2
(2, 4)
8
int32
4
32


#### How to access elements from 2-d array

In [62]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [63]:
b[0]          # row index

array([1, 2, 3, 4])

In [64]:
b[1]

array([5, 6, 7, 8])

In [66]:
b[0,0]   # Row index,element index

1

In [68]:
b[1,3]

8

In [69]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
[4,8]

In [71]:
b[:,3]

array([4, 8])

In [72]:
b[:,-1]

array([4, 8])

In [ ]:
[3 4
 7 8]

In [74]:
b[:,2:4]

array([[3, 4],
       [7, 8]])

In [76]:
b[:,::2]

array([[1, 3],
       [5, 7]])