### Day Objectives:
    - Numpy Arrays
    - Pandas

In [1]:
import numpy as np

In [ ]:
#####  How to create 3-d array in numpy:

##### 3-d array:
    - it is a combination of more than one 2-d array
    - syntax:
        np.array([[[e1,e2,e3,e4],[e1,e2,e3,e4]],[[e1,e2,e3,e4],[e1,e2,e3,e4]]])
        

In [2]:
c=np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[9,5,1,4]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [9]:
print(c)
print(c.ndim)
print(c.shape) # array size,row size,column size
print(c.dtype)
print(c.size)
print(c.itemsize)
print(c.nbytes)

[[[1 2 3 4]
  [5 6 7 8]]

 [[5 6 7 8]
  [9 5 1 4]]]
3
(2, 2, 4)
int32
16
4
64


#### How to access elements from 3-d array:

In [10]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [11]:
c[0]          ### array index

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
c[1]

array([[5, 6, 7, 8],
       [9, 5, 1, 4]])

In [14]:
c[0,1]   ### array index,row index

array([5, 6, 7, 8])

In [15]:
c[0,0]

array([1, 2, 3, 4])

In [16]:
c[1]

array([[5, 6, 7, 8],
       [9, 5, 1, 4]])

In [17]:
c[1,0]

array([5, 6, 7, 8])

In [18]:
c[1,1]

array([9, 5, 1, 4])

In [19]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [22]:
c[0,0,3]     # array index,row index,element index

4

In [23]:
c[1,0,3]

8

In [25]:
c[0,0,3],c[1,0,3]

(4, 8)

In [28]:
c[:,0,3]

array([4, 8])

In [29]:
c[:,0,-1]

array([4, 8])

In [30]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [ ]:
2 3
6 7

In [33]:
c[:,0,1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
2 3
6 7

6 7
5 1

In [34]:
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[5, 6, 7, 8],
        [9, 5, 1, 4]]])

In [37]:
c[:,:,1:3]

array([[[2, 3],
        [6, 7]],

       [[6, 7],
        [5, 1]]])

In [38]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [39]:
print(len(dir(np)))

598


#### Reshape of an array:
    - it returns new shape of original array
    - syntax:
            np.reshape(rowsize,column size)

In [40]:
### 1-d array
x=np.arange(1,21)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
### 2-d array
x1=x.reshape(4,5)    #4 5,5 4,1 20,20 1
x1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [42]:
x.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
##### 3-d array
x2=x.reshape(2,5,2)  # 2 5 2,5 2 2,4 5 1,5 4 1
x2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [44]:
x.reshape(5,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

### How to user reshape to arange function:

In [46]:
x3=np.arange(1,37).reshape(6,6)
x3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [47]:
x3=np.arange(1,37).reshape(9,4)
x3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

##### iteration of an array:

In [48]:
a=np.array([45,56,67,78,89,90])
a

array([45, 56, 67, 78, 89, 90])

In [50]:
### 1-d array looping:
for i in  a:
    print(i,end=" ")

45 56 67 78 89 90 

In [51]:
### 2-d array
a1=a.reshape(2,3)
a1

array([[45, 56, 67],
       [78, 89, 90]])

In [54]:
for i in a1:
    for j in i:
        print(j,end=" ")
    

45 56 67 78 89 90 

In [55]:
#### 3-d
a2=a.reshape(2,3,1)
a2

array([[[45],
        [56],
        [67]],

       [[78],
        [89],
        [90]]])

In [59]:
for i in a2:
    for j in i:
        for k in j:
            print(k,end=" ")

45 56 67 78 89 90 

### nditer():
        np.nditer()

In [60]:
for i in np.nditer(a2):
    print(i,end=" ")

45 56 67 78 89 90 

In [63]:
for i in np.nditer(a2):
    print(i,end=" ")

45 56 67 78 89 90 

#### Arrays concatenation:
        np.concatenate((array 1,array 2))

In [65]:
i=np.arange(1,11)
j=np.arange(11,21)
result=np.concatenate((i,j))
print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [68]:
#### 2-d 
i1=i.reshape(5,2)
j1=j.reshape(5,2)
print(i1)
print(j1)
res=np.concatenate((i1,j1))
print(res)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [72]:
##### 3-d
i2=i.reshape(2,5,1)
j2=j.reshape(2,5,1)
# print(i2)
# print(j2)
con=np.concatenate((i2,j2))
print(con)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]]]


#### Stastistical And Math Operations on Arrays:

In [73]:
a

array([45, 56, 67, 78, 89, 90])

In [74]:
np.min(a) # min  value

45

In [75]:
np.max(a)# max value

90

In [76]:
np.argmax(a)  # it return max index value

5

In [77]:
a.argmax()

5

In [80]:
np.argmin(a) # it returns min index value

0

In [81]:
a.argmin()

0

In [82]:
np.mean(a)  # it return mean value of the array

70.83333333333333

In [83]:
np.median(a)

72.5

In [84]:
np.std(a)

16.587311080729418

In [85]:
np.var(a)

275.1388888888889

In [88]:
np.sum(a)

425

In [106]:
a1

array([[45, 56, 67],
       [78, 89, 90]])

In [ ]:
0--->column wise
1--->row wise

In [108]:
np.sum(a1,1)

array([168, 257])

In [109]:
np.sum(a1,0)

array([123, 145, 157])

In [89]:
np.sqrt(a)

array([6.70820393, 7.48331477, 8.18535277, 8.83176087, 9.43398113,
       9.48683298])

In [90]:
np.exp(a)

array([3.49342711e+19, 2.09165950e+24, 1.25236317e+29, 7.49841700e+33,
       4.48961282e+38, 1.22040329e+39])

In [94]:
np.mod(a,2)

array([1, 0, 1, 0, 1, 0], dtype=int32)

In [96]:
np.power(a,2)  # square value

array([2025, 3136, 4489, 6084, 7921, 8100], dtype=int32)

In [97]:
np.power(a,3)  # cube

array([ 91125, 175616, 300763, 474552, 704969, 729000], dtype=int32)

In [99]:
np.multiply(a,6)

array([270, 336, 402, 468, 534, 540])

In [100]:
np.divide(a,6)

array([ 7.5       ,  9.33333333, 11.16666667, 13.        , 14.83333333,
       15.        ])

In [101]:
b=np.array([1+2j,2+3j,10+4j])
b

array([ 1.+2.j,  2.+3.j, 10.+4.j])

In [102]:
np.real(b)

array([ 1.,  2., 10.])

In [103]:
np.imag(b)

array([2., 3., 4.])

In [105]:
np.reciprocal(a,dtype=float)

array([0.02222222, 0.01785714, 0.01492537, 0.01282051, 0.01123596,
       0.01111111])

In [91]:
#### trignometric functions
np.sin(a)

array([ 0.85090352, -0.521551  , -0.85551998,  0.51397846,  0.86006941,
        0.89399666])

In [92]:
np.cos(a)

array([ 0.52532199,  0.85322011, -0.5177698 , -0.85780309,  0.51017704,
       -0.44807362])

In [93]:
np.tan(a)

array([ 1.61977519, -0.61127369,  1.65231726, -0.59918   ,  1.68582537,
       -1.99520041])

In [ ]:
##### Logrithimic values

In [110]:
a

array([45, 56, 67, 78, 89, 90])

In [111]:
np.log(a)

array([3.80666249, 4.02535169, 4.20469262, 4.35670883, 4.48863637,
       4.49980967])

In [112]:
np.log2(a)

array([5.4918531 , 5.80735492, 6.06608919, 6.28540222, 6.47573343,
       6.4918531 ])

In [113]:
np.log10(a)

array([1.65321251, 1.74818803, 1.8260748 , 1.8920946 , 1.94939001,
       1.95424251])

In [114]:
a1

array([[45, 56, 67],
       [78, 89, 90]])

In [115]:
a1.T

array([[45, 78],
       [56, 89],
       [67, 90]])

#### Ravel():
    - ravel is a function used to create copy of the original array.when any changes made in the dupliate array those will also applied in the original array.



#### Flatten():
    - faltten is a function used to create copy of the original array.when any changes made in the duplicate array those changes will not applied in the original array. 

In [116]:
### ravel()

original=np.arange(1,11)
original

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
copy=original.ravel()
copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
copy[0]=99

In [121]:
copy

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
original

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#### flatten()

In [124]:
original1=np.arange(11,21)
original1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
duplicate=original1.flatten()
duplicate

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [130]:
duplicate[1]=100

In [132]:
duplicate

array([ 11, 100,  13,  14,  15,  16,  17,  18,  19,  20])

In [133]:
original1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

#### random methods:
    - np.random.randint()
    - np.random.rand()
    - np.random.randn()

In [141]:
np.random.randint(100)

53

In [146]:
np.random.randint(100,size=(10))

array([91, 10, 13, 77, 84, 69, 97, 32, 84, 17])

In [154]:
np.random.randint(36,size=(9,4))


array([[ 5,  7, 25, 31],
       [ 4, 34, 32,  9],
       [18, 17, 24, 26],
       [16, 32,  2, 13],
       [21,  5, 23, 30],
       [32, 28, 23,  5],
       [27,  4, 26, 35],
       [ 3, 20,  7, 29],
       [16, 27, 34,  4]])

In [ ]:
#### rand()-- it returns float value within 0 and 1 range

In [168]:
np.random.rand(20)

array([0.56294006, 0.58476408, 0.16740527, 0.9645577 , 0.7063448 ,
       0.390791  , 0.74548568, 0.22014709, 0.24954894, 0.44311309,
       0.98526818, 0.20617223, 0.10777938, 0.58278687, 0.11708289,
       0.20946713, 0.48368801, 0.96707925, 0.68513172, 0.83438364])

In [158]:
np.random.rand()

0.6914609035971311

In [ ]:
##### randn--->it returns positive and negetive values in the given range

In [162]:
np.random.randn(10)

array([-0.01377521,  2.20895256,  0.74952431,  0.38273412, -1.40454631,
        1.60668352,  0.41583871,  0.14162679, -1.22888251, -0.70689412])

In [ ]:
#### random.normal

In [178]:
np.random.normal()

1.557625375767997

#### Array Filtering

In [179]:
k=np.array([10,14,22,7,12,95,20])
l=[False,True,True,True,True,False,False]
fil=k[l]
print(fil)

[14 22  7 12]
